POST http://localhost:3001/api/jugadores
Content-Type: application/json

{
    "nombre": "Lionel Messi",
    "foto": "https://www.fundacionkonex.org/custom/web/data/imagenes/repositorio/2021/03/12/16575/2021031202544061e0e3f25c3041f849de6b510817fb34.jpg"
}

###
POST http://localhost:3001/api/jugadores
Content-Type: application/json

{
   
}